import { NextResponse } from "next/server";
import { auth, currentUser } from "@clerk/nextjs/server";
import { db } from "@/lib/prisma";

export async function GET() {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Use prisma.conversation (lowercase) as generated by Prisma Client
    const conversations = await db.conversation.findMany({
      where: { userId: userId },
      orderBy: { createdAt: "desc" },
    });

    // CRITICAL: Always return an array. 
    // If conversations is null/undefined, return [] to prevent frontend crashes.
    return NextResponse.json(conversations || []);
  } catch (error) {
    console.error("GET_CONVERSATIONS_ERROR:", error);
    // Return empty array on error so the frontend map() doesn't fail
    return NextResponse.json([], { status: 500 });
  }
}

export async function POST() {
  try {
    const { userId } = await auth();
    const clerkUser = await currentUser();

    if (!userId || !clerkUser) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // 1. Sync User using capital 'User' reference logic from your schema
    await prisma.user.upsert({
      where: { clerkUserId: userId },
      update: { imageUrl: clerkUser.imageUrl },
      create: {
        clerkUserId: userId,
        email: clerkUser.emailAddresses[0].emailAddress,
        name: `${clerkUser.firstName || ""} ${clerkUser.lastName || ""}`.trim(),
        imageUrl: clerkUser.imageUrl,
      },
    });

    // 2. Create the conversation
    const convo = await prisma.conversation.create({
      data: {
        userId: userId,
        title: "New Career Chat",
      },
    });

    return NextResponse.json(convo);
  } catch (error) {
    console.error("POST_CONVERSATION_ERROR:", error);
    return NextResponse.json(
      { error: "Failed to create chat", details: error.message },
      { status: 500 }
    );
  }
}